name: Build and Push Docker Image

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change image name to lowercase
      run: |
        echo "IMAGE_NAME=$(echo ${REPOSITORY_NAME} | awk '{print tolower($0)}')" >> ${GITHUB_ENV}

    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        dockerfile: Dockerfile
